Do not wait for batch pods to be deleted during cleanup tasks
Some of the tasks that are taking the longest to finish as reported by
Ansible recap are the tasks that involves cleaning up pods created
during migration for export-import.

This change speedup those tasks by do not waiting for the pod deletion
(adding --wait=false to kubectl delete commands).

Also, append "-wa" to dar backup command so the migration can be
successfully restarted in case of any failure during the migration
backup step

Test Plan:
PASS: LVM export-import migration
PASS: Rook-Ceph export-import migration

Story: 2011728
Task: 55416
Change-Id: Icf07cf07ebf428966b4b838eec38df8dea068c3c
Signed-off-by: Alyson Deives Pereira <alyson.deivespereira@windriver.com>

diff --git a/playbookconfig/src/playbooks/roles/storage-backend-migration/export/tasks/create_cephfs_backup_single_pvc.yaml b/playbookconfig/src/playbooks/roles/storage-backend-migration/export/tasks/create_cephfs_backup_single_pvc.yaml
--- a/playbookconfig/src/playbooks/roles/storage-backend-migration/export/tasks/create_cephfs_backup_single_pvc.yaml
+++ b/playbookconfig/src/playbooks/roles/storage-backend-migration/export/tasks/create_cephfs_backup_single_pvc.yaml
@@ -12,10 +12,10 @@
     BKP_FILE_HOST="${CEPHFS_BACKUP_DIR}/${BACKUP_NAME}"
 
     echo "Starting backup of /data/{{ pvc.name }}/..."
-    kubectl exec -n {{ cephfs_pvc_namespace }} {{ batch_pod_name }} -- dar -c "$BKP_FILE_POD" -R "/data/{{ pvc.name }}/" -z -ah -Q || { echo "ERROR: dar backup failed, possibly out of space"; exit 1; }
+    kubectl exec -n {{ cephfs_pvc_namespace }} {{ batch_pod_name }} -- dar -c "$BKP_FILE_POD" -R "/data/{{ pvc.name }}/" -z -ah -Q -wa || { echo "ERROR: dar backup failed, possibly out of space"; exit 1; }
 
     echo "Verifying backup integrity..."
-    kubectl exec -n {{ cephfs_pvc_namespace }} {{ batch_pod_name }} -- dar -t "$BKP_FILE_POD" -Q || { echo "ERROR: dar integrity check failed"; exit 1; }
+    kubectl exec -n {{ cephfs_pvc_namespace }} {{ batch_pod_name }} -- dar -t "$BKP_FILE_POD" -Q -wa || { echo "ERROR: dar integrity check failed"; exit 1; }
   environment:
     KUBECONFIG: "{{ kubeconfig }}"
     PVC_NAME: "{{ cephfs_pvc_namespace }}-{{ pvc.name }}"
